openapi: 3.1.0
x-stoplight:
  id: cf9otymsap8rh
info:
  title: Authentication
  version: '1.0'
  description: ''
  summary: ''
servers:
  - url: 'https://api.icount.co.il/api/v3.php/auth'
paths:
  /login:
    post:
      summary: Start session
      operationId: post-login
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    api:
                      version: 3
                      tz: 2
                      ts: 1699275163.1748
                      lang: he
                      rid: 831608358
                      module: auth
                      method: login
                    status: true
                    reason: OK
                    sid: 6548e19b2c02c922612458
                    cid: liavy
                    user: api
                    user_id: 3
                    user_info:
                      user_id: 3
                      username: api
                      email: liavapi@icount.co.il
                      phone: ''
                      mobile: ''
                      first_name: Liav
                      last_name: Liav
                      full_name: Liav Liav
                      first_name_he: Liav
                      last_name_he: Liav
                      full_name_he: Liav Liav
                      first_name_en: API
                      last_name_en: API
                      full_name_en: API API
                      profile_image: ''
                      priv_level: 4
                      job_type_id: 0
                      priv_name: מנהל
                      intercom_user_id: '110144163.3'
                      intercom_user_hash: 205f9957e7c2667c1f2a69e6de79819435d495c58271df126c5672f1835c8e45
                      job_type_name: לא מוגדר / כללי
                      job_type_hours:
                        '100': 32400
                        '125': 0
                        '150': 0
                        '175': 0
                        '200': 0
                    company_info:
                      about: ''
                      addressCity: ''
                      addressCity_en: ''
                      addressCity_he: ''
                      addressNum: ''
                      addressState: ''
                      addressStreet: ''
                      addressStreet_en: ''
                      addressStreet_he: ''
                      addressZip: '0'
                      businessName: LIAV TEST
                      businessNameSubTitle: ''
                      businessNameSubTitle_en: ''
                      businessNameSubTitle_he: ''
                      businessName_en: ''
                      businessName_he: LIAV TEST
                      businessType: '1'
                      businessTypeAbbr: ע.מ.
                      businessTypeAbbr_en: VAT ID
                      businessTypeAbbr_he: ע.מ.
                      businessTypeName: עצמאי / עוסק מורשה
                      businessTypeName_en: Sole Proprietor
                      businessTypeName_he: עצמאי / עוסק מורשה
                      country_en: ''
                      ecosystem: il
                      email: liavy@icount.co.il
                      facebook: ''
                      fax: ''
                      logo: null
                      mobile: ''
                      operating_hours: ''
                      phone: ''
                      site: ''
                      telegram: ''
                      twitter: ''
                      updated: '2023-10-01 15:30:43'
                      updated_by: '1'
                      vat_id: '208915843'
                      youtube: ''
                      start_date: '2023-10-01'
                      expiry_date: '2024-12-31'
                      is_trial: true
                      require_billing: true
                      is_non_profit: false
                      is_tax_exempt: false
                      is_vat_exempt: false
                      no_vat_business: false
                      system_type: std
                      is_express: false
                      is_omb: false
                      icon: null
              examples:
                Example 1:
                  value:
                    api:
                      version: 3
                      tz: 2
                      ts: 1700143271.9638
                      lang: he
                      rid: 838866177
                      module: auth
                      method: login
                    status: true
                    reason: OK
                    sid: 655610a1ec910346010129
                    cid: icount
                    user: api
                    user_id: 3
                    user_info:
                      user_id: 3
                      username: api
                      email: api@icount.co.il
                      phone: ''
                      mobile: ''
                      first_name: API
                      last_name: iCount
                      full_name: iCount API
                      first_name_he: אייקאונט
                      last_name_he: מערכות
                      full_name_he: אייקאונט מערכות
                      first_name_en: API
                      last_name_en: iCount
                      full_name_en: iCount API
                      profile_image: ''
                      priv_level: 4
                      job_type_id: 0
                      priv_name: מנהל
                      intercom_user_id: '110645163.3'
                      intercom_user_hash: 205aff57e7c2667c1f2a69e6de714444d495c58271df126c5672f1835c8e45
                      job_type_name: לא מוגדר / כללי
                      job_type_hours:
                        '100': 32400
                        '125': 0
                        '150': 0
                        '175': 0
                        '200': 0
      x-stoplight:
        id: iweg9ar3xqpfu
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cid:
                  type: string
                  x-stoplight:
                    id: 3fjgng9ix4q08
                  description: Company identifier
                user:
                  type: string
                  x-stoplight:
                    id: 9qjibobgdcgy4
                  description: Username
                pass:
                  type: string
                  x-stoplight:
                    id: vkbb6ixbv95qk
                  description: Password
                require_module:
                  x-stoplight:
                    id: z2hybuwsrrjac
                  description: Require specific module access
                  type: string
                require_priv:
                  type: number
                  x-stoplight:
                    id: 3kpn4w2v6g6m3
                  description: Require privilege level
                  format: float
                get_company_info:
                  type: boolean
                  x-stoplight:
                    id: wh20w3owk0z0i
                  description: Get company information
                get_settings:
                  type: boolean
                  x-stoplight:
                    id: sb0osyq8tvuvo
                  description: Get company settings as well
                get_bank_accounts:
                  type: boolean
                  x-stoplight:
                    id: m7pglmeitaq7u
                  description: Get company bank accounts list
                list_type:
                  type: string
                  x-stoplight:
                    id: 2zgtx8o17et4y
                  description: List type (array|object).
              required:
                - cid
                - user
                - pass
            examples:
              Example 1:
                value:
                  cid: companyname
                  user: username
                  pass: password
        description: A session ID remains valid for 20 minutes from the last request—each new request resets the expiration timer.
  /logout:
    post:
      summary: Close session
      operationId: post-logout
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Example 1:
                  value:
                    api:
                      version: 3
                      tz: 2
                      ts: 1700144931.6464
                      lang: he
                      rid: 811112851
                      module: auth
                      method: logout
                    status: true
                    reason: BYE
      x-stoplight:
        id: j7lfsfv5agmbz
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: boolean
                  x-stoplight:
                    id: 1l3mr73yz0801
                  description: Operation status
                reason:
                  type: string
                  x-stoplight:
                    id: d9mnjuqes344d
                  description: Error code
                error_description:
                  type: string
                  x-stoplight:
                    id: riq7vqfglzd4v
                  description: Short error descripion
                error_details:
                  type: array
                  x-stoplight:
                    id: nnwfy42va0jzx
                  description: Detailed error messages list
                  items:
                    x-stoplight:
                      id: lf8eznn6qp6zh
                    type: string
              required:
                - status
  /info:
    post:
      summary: Get auth session details
      operationId: post-info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Example 1:
                  value:
                    api:
                      version: 3
                      tz: 2
                      ts: 17005554725.0502
                      lang: he
                      rid: 8384440709
                      module: auth
                      method: info
                    status: true
                    reason: OK
                    sid: '654444431062631606'
                    cid: icount
                    user: api
                    user_id: 3
                    user_info:
                      user_id: 3
                      username: api
                      email: api@icount.co.il
                      phone: ''
                      mobile: ''
                      first_name: iCount
                      last_name: API
                      full_name: iCount API
                      first_name_he: iCount
                      last_name_he: Hebrew
                      full_name_he: iCount Hebrew
                      first_name_en: iCount
                      last_name_en: English
                      full_name_en: iCount English
                      profile_image: ''
                      priv_level: 4
                      job_type_id: 0
                      priv_name: מנהל
                      intercom_user_id: '110444163.3'
                      intercom_user_hash: 213f9957e7gagg4g9419435d495c58271df126c5672f1835c14
                      job_type_name: לא מוגדר / כללי
                      job_type_hours:
                        '100': 32400
                        '125': 0
                        '150': 0
                        '175': 0
                        '200': 0
      x-stoplight:
        id: d7u4t41xzzu6d
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                get_company_info:
                  type: boolean
                  x-stoplight:
                    id: mmkyvg7cj2wi4
                  description: Get company information
                get_settings:
                  type: boolean
                  x-stoplight:
                    id: 19dqe59i801d1
                  description: Get company settings as well
                get_bank_accounts:
                  type: boolean
                  x-stoplight:
                    id: dz3i0i7s4z1sq
                  description: Get company bank accounts list
                list_type:
                  type: string
                  x-stoplight:
                    id: ts16ahargjvkc
                  description: List type (array|object).
            examples:
              Example 1:
                value:
                  get_company_info: true
                  get_settings: true
                  get_bank_accounts: true
                  list_type: string
components:
  schemas:
    iCountUserPrivLevel:
      title: iCountUserPrivLevel
      x-stoplight:
        id: y232n1ngb29ko
      type: object
      properties:
        id:
          type: number
          x-stoplight:
            id: o93vxne0wkdzw
          format: float
      description: User privilege level
    iCountUserPrivLevelInfo:
      title: iCountUserPrivLevelInfo
      x-stoplight:
        id: q6totsagvxy7q
      type: object
      properties:
        priv_level:
          $ref: '#/components/schemas/iCountUserPrivLevel'
          x-stoplight:
            id: 50ccm3s3cy6q0
          description: User privilege level
        priv_name:
          type: string
          x-stoplight:
            id: vadnmu9bl3t9y
          description: User privilege level name
      required:
        - priv_level
        - priv_name
      description: User privilege level information
    iCountUserInfo:
      title: iCountUserInfo
      x-stoplight:
        id: u3hg22fxcl7kf
      type: object
      properties:
        user_id:
          type: integer
          x-stoplight:
            id: jw6vepcmnug3l
          description: User ID
        username:
          type: string
          x-stoplight:
            id: 5m93j0819qyet
          description: Username
        email:
          type: string
          x-stoplight:
            id: 5sd9hj3k3wxov
          description: Email address
        first_name:
          type: string
          x-stoplight:
            id: lrc2pzmcs1cj0
          description: First name
        last_name:
          type: string
          x-stoplight:
            id: oms2w6lxuksbd
          description: Last name
        full_name:
          type: string
          x-stoplight:
            id: fspwk6g6l9fje
          description: Full name
        priv_level:
          $ref: '#/components/schemas/iCountUserPrivLevel'
          x-stoplight:
            id: awdnlsmxllk6m
          description: Privilege level
        priv_name:
          type: string
          x-stoplight:
            id: 2g1sj4t0dqpxk
          description: Privilege level name
      required:
        - user_id
        - username
        - email
        - first_name
        - last_name
        - full_name
        - priv_level
        - priv_name
      description: User information
    iCountCompanyInfo:
      title: iCountCompanyInfo
      x-stoplight:
        id: toznl1i77hxut
      type: object
      properties:
        vat_id:
          type: string
          x-stoplight:
            id: vye9a2jzmj7ck
          description: Company VAT ID
        businessName:
          type: string
          x-stoplight:
            id: ffq5sca4ag6n0
          description: Company name (current language)
        businessName_he:
          type: string
          x-stoplight:
            id: z71jt4cgeajtb
          description: Company name (hebrew)
        businessName_en:
          type: string
          x-stoplight:
            id: rbm09jtuyy8f3
          description: Company name (english)
        businessNameSubTitle:
          type: string
          x-stoplight:
            id: z60e7594nbwvh
          description: Company name sub-title (current language)
        businessNameSubTitle_he:
          type: string
          x-stoplight:
            id: 1dwmwwk8cyif6
          description: Company name sub-title (hebrew)
        businessNameSubTitle_en:
          type: string
          x-stoplight:
            id: a0yz5kopn7xsa
          description: Company name sub-title (english)
        businessType:
          type: integer
          x-stoplight:
            id: ksg5xaq7jisp2
          description: Business type ID
        businessTypeName:
          type: string
          x-stoplight:
            id: fqhxwk87kiy8l
          description: Business type name (current language)
        businessTypeName_he:
          type: string
          x-stoplight:
            id: qkmze56fowjb7
          description: Business type name (hebrew)
        businessTypeName_en:
          type: string
          x-stoplight:
            id: s3qapjerb2hl1
          description: Business type name (english)
        businessTypeAbbr:
          type: string
          x-stoplight:
            id: 3s8aoki4lzia0
          description: Business type abbreviation (current language)
        businessTypeAbbr_he:
          type: string
          x-stoplight:
            id: udjpuzlcqa3ye
          description: Business type abbreviation (hebrew)
        businessTypeAbbr_en:
          type: string
          x-stoplight:
            id: 5k7w9twa4d8fk
          description: Business type abbreviation (english)
        is_non_profit:
          type: boolean
          x-stoplight:
            id: mziwe15rff1un
          description: Is non-profit organization?
        is_tax_exempt:
          type: boolean
          x-stoplight:
            id: fzvbyda290q48
          description: Is tax-exemmpt company? (small private business)
        is_vat_exempt:
          type: boolean
          x-stoplight:
            id: qkwtxbjwyrpjr
          description: Is the company VAT-exempt (non-profit OR small private business)
        email:
          type: string
          x-stoplight:
            id: lsc330h4l2sej
          description: Company primary email address
        phone:
          type: string
          x-stoplight:
            id: yqgxyjxk8ik10
          description: Company primary phone number
        fax:
          type: string
          x-stoplight:
            id: 3fy5w8h6mpzmm
          description: Company primary fax number
        logo:
          type: string
          x-stoplight:
            id: lh3vdmo776ren
          description: Company logo URL
        site:
          type: string
          x-stoplight:
            id: gwg1l0fbbjn2v
          description: Company website URL
      required:
        - vat_id
        - businessName
        - businessName_he
        - businessName_en
        - businessNameSubTitle
        - businessNameSubTitle_he
        - businessNameSubTitle_en
        - businessType
        - businessTypeName
        - businessTypeName_he
        - businessTypeName_en
        - businessTypeAbbr
        - businessTypeAbbr_he
        - businessTypeAbbr_en
        - is_non_profit
        - is_tax_exempt
        - is_vat_exempt
        - email
        - phone
        - fax
        - logo
        - site
      description: Company information
    iCountCompanySettings:
      title: iCountCompanySettings
      x-stoplight:
        id: wzalcuk22akvu
      type: object
      properties:
        cc_enabled:
          type: boolean
          x-stoplight:
            id: wu6hsls0p6aze
          description: Enable Credit-Card payment support (cc/bill)?
        cc_require_cvv:
          type: boolean
          x-stoplight:
            id: 0oe9hu84wfyir
          description: Require CVV field in Credit-Card payment?
        cc_storage_enabled:
          type: boolean
          x-stoplight:
            id: 43qugndqjea8r
          description: Is Credit-Card storage enabled?
        pos_enabled:
          type: boolean
          x-stoplight:
            id: up98cicanbase
          description: Enable POS (Point-Of-Sale)?
        iqr_enabled:
          type: boolean
          x-stoplight:
            id: b7p3g48xkg8nb
          description: Enable iQR data QR code on documents?
        hk_enabled:
          type: boolean
          x-stoplight:
            id: 0l0wmo0kuh14i
          description: Enable Standing Orders?
        expense_enabled:
          type: boolean
          x-stoplight:
            id: yu66d27udmqyo
          description: Enable Expenses?
        inventory_enabled:
          type: boolean
          x-stoplight:
            id: yf9fkw76jgcvm
          description: Enable Inventory management?
        inventory_min_stock_alerts:
          type: boolean
          x-stoplight:
            id: bunsiqq0csdws
          description: Enable Inventory min-stock alerts?
        punchclock_enabled:
          type: boolean
          x-stoplight:
            id: g5sh3bqt1t8a3
          description: Enable Punchclock?
        punchclock_require_location:
          type: boolean
          x-stoplight:
            id: h74xo7bouno43
          description: Punchclock requires location? (do not allow punch-in/punch-out without location)
        project_management_enabled:
          type: boolean
          x-stoplight:
            id: ndn8rflgticho
          description: Enable Project management?
        crm_enabled:
          type: boolean
          x-stoplight:
            id: 8719thizflxx9
          description: Enable CRM?
        file_manager_enabled:
          type: boolean
          x-stoplight:
            id: 8dkcx349fi6ec
          description: Enable File Manager?
        file_upload_enabled:
          type: boolean
          x-stoplight:
            id: hgwdj4s9mw90w
          description: Enable File uploads?
        display_decimals:
          type: integer
          x-stoplight:
            id: 6v1zwokbesmca
          description: Number of decimals for prices before tax
        display_decimals_incvat:
          type: integer
          x-stoplight:
            id: yrz0k7zkksygt
          description: Number of decimals for prices including tax
        multi_deduction:
          type: boolean
          x-stoplight:
            id: 0keu3twn9jngs
          description: Enable multiple deduction types?
        long_description_enabled:
          type: boolean
          x-stoplight:
            id: la1bja6hdr13b
          description: Enable long_description support in items (document and inventory)
      required:
        - cc_enabled
        - hk_enabled
        - expense_enabled
        - inventory_enabled
        - punchclock_enabled
        - project_management_enabled
        - crm_enabled
        - file_manager_enabled
        - file_upload_enabled
        - display_decimals
        - display_decimals_incvat
        - multi_deduction
        - long_description_enabled
      description: Company settings
    iCountCompanyBankAccount:
      title: iCountCompanyBankAccount
      x-stoplight:
        id: ru58n1yxg3jj7
      type: object
      properties:
        account_id:
          type: string
          x-stoplight:
            id: 1t1aw7pb15e6a
          description: Bank account ID
        bank:
          type: string
          x-stoplight:
            id: mn81hpodkyrw9
          description: Bank number
        branch:
          type: string
          x-stoplight:
            id: dd27c0dakg4ub
          description: Bank ranch number
        account:
          type: string
          x-stoplight:
            id: m5hqtr7feudbj
          description: Bank account number
        currency_id:
          type: integer
          x-stoplight:
            id: vwxr7cr4usfx7
          description: Currency ID
        title:
          type: string
          x-stoplight:
            id: b4sxsfib5ng1h
          description: Bank account title
      required:
        - account_id
        - bank
        - branch
        - account
        - currency_id
        - title
      description: Bank account information
    iCountCompanyStoredFile:
      title: iCountCompanyStoredFile
      x-stoplight:
        id: 1ptqisvua6hpd
      type: object
      properties:
        type:
          type: string
          x-stoplight:
            id: esybxffd31j21
          description: 'Document type (eg, books_approval, deduction_approval, etc)'
        title:
          type: string
          x-stoplight:
            id: f555ctqimhbcs
          description: Document type title (display name)
        url:
          type: string
          x-stoplight:
            id: ydp1m18v32dzd
          description: 'Document URL, if exists'
        comment:
          type: string
          x-stoplight:
            id: v9oamwkdx0x0y
          description: Comment
      required:
        - type
        - title
      description: Company stored file information
